use healthcare;

create database healthcare;

select * from org_data;

SELECT TYPE_CNTRL AS TYPE_HOSP, 
       CONCAT(ROUND(SUM(DIS_TOT) / 1000, 1), 'K') AS DIS_TOT
FROM org_data
GROUP BY TYPE_CNTRL;


SELECT 
  LEFT(YEAR_QTR, 4) AS YEAR, 
  RIGHT(YEAR_QTR, 1) AS QTR, 
  CONCAT(ROUND(SUM(DAY_TOT) / 1000, 1), 'K') AS DAY_TOT
FROM org_data
GROUP BY LEFT(YEAR_QTR, 4), RIGHT(YEAR_QTR, 1);

SELECT 
  TYPE_CNTRL AS TYPE_HOSP, 
  CONCAT(ROUND(SUM(NET_PAT_REV_CC) / 1000000, 1), 'M') AS NET_TOT_in_Million
FROM org_data
GROUP BY TYPE_CNTRL;

SELECT COUNTY_NAME, 
       CONCAT(ROUND(SUM(NET_PAT_REV_CC) / 1000000, 1), 'M') AS NET_TOT
FROM org_data
GROUP BY COUNTY_NAME;

SELECT TYPE_CNTRL AS TYPE_HOSP, 
       COUNT(DISTINCT FAC_NAME) AS NO_OF_HOSPITAL
FROM org_data
GROUP BY TYPE_CNTRL;

SELECT TYPE_CNTRL AS TYPE_HOSP, 
       CONCAT(ROUND(SUM(DAY_TOT) / 1000, 1), 'K') AS TOTAL_PATIENT
FROM org_data
GROUP BY TYPE_CNTRL;

SELECT LEFT(YEAR_QTR, 4) AS YEAR, 
       CONCAT(ROUND(SUM(NET_PAT_REV_CC) / 1000000, 2), 'M') AS NET_TOT
FROM org_data
GROUP BY LEFT(YEAR_QTR, 4);


WITH quarterly_data AS (
  SELECT 
    YEAR(STR_TO_DATE(END_DATE, '%m/%d/%Y')) AS YEAR, 
    QUARTER(STR_TO_DATE(END_DATE, '%m/%d/%Y')) AS QUARTER, 
    SUM(NET_PAT_REV_CC) AS REVENUE
  FROM org_data
  GROUP BY YEAR(STR_TO_DATE(END_DATE, '%m/%d/%Y')), QUARTER(STR_TO_DATE(END_DATE, '%m/%d/%Y'))
),
lagged_quarters AS (
  SELECT 
    YEAR, 
    QUARTER, 
    REVENUE,
    LAG(REVENUE) OVER (PARTITION BY QUARTER ORDER BY YEAR) AS PREV_YEAR_SAME_QUARTER
  FROM quarterly_data
)
SELECT 
  YEAR, 
  QUARTER,
  CONCAT(ROUND(REVENUE / 1000000, 2), 'M') AS REVENUE_M,
  CONCAT(ROUND(PREV_YEAR_SAME_QUARTER / 1000000, 2), 'M') AS PREV_YEAR_SAME_QUARTER,
  CONCAT(ROUND((REVENUE - PREV_YEAR_SAME_QUARTER) / PREV_YEAR_SAME_QUARTER * 100, 2), '%') AS QOY_GROWTH_PERCENT
FROM lagged_quarters
ORDER BY YEAR, QUARTER;

WITH monthly_data AS (
  SELECT 
    YEAR(STR_TO_DATE(END_DATE, '%m/%d/%Y')) AS YEAR, 
    MONTH(STR_TO_DATE(END_DATE, '%m/%d/%Y')) AS MONTH, 
    SUM(NET_PAT_REV_CC) AS REVENUE
  FROM org_data
  GROUP BY YEAR(STR_TO_DATE(END_DATE, '%m/%d/%Y')), MONTH(STR_TO_DATE(END_DATE, '%m/%d/%Y'))
),
lagged_months AS (
  SELECT 
    YEAR, 
    MONTH, 
    REVENUE,
    LAG(REVENUE) OVER (PARTITION BY MONTH ORDER BY YEAR) AS PREV_YEAR_SAME_MONTH
  FROM monthly_data
)
SELECT 
  YEAR, 
  MONTH,
  CONCAT(ROUND(REVENUE / 1000000, 2), 'M') AS REVENUE,
  CONCAT(ROUND(PREV_YEAR_SAME_MONTH / 1000000, 2), 'M') AS PREV_YEAR_SAME_MONTH,
  CONCAT(ROUND((REVENUE - PREV_YEAR_SAME_MONTH) / PREV_YEAR_SAME_MONTH * 100, 2), '%') AS MOM_GROWTH_PERCENT
FROM lagged_months
ORDER BY YEAR, MONTH;

WITH latest_year_month_day AS (
  SELECT MAX(STR_TO_DATE(END_DATE, '%m/%d/%Y')) AS latest_date,
         YEAR(MAX(STR_TO_DATE(END_DATE, '%m/%d/%Y'))) AS latest_date_year,
         MONTH(MAX(STR_TO_DATE(END_DATE, '%m/%d/%Y'))) AS latest_date_month
  FROM org_data
)
SELECT 
  YEAR(STR_TO_DATE(END_DATE, '%m/%d/%Y')) AS YEAR,
  CONCAT(ROUND(SUM(CASE WHEN MONTH(STR_TO_DATE(END_DATE, '%m/%d/%Y')) <= latest_date_month THEN NET_PAT_REV_CC ELSE 0 END) / 1000000, 2), 'M') AS YTD,
  CONCAT(ROUND(SUM(CASE WHEN MONTH(STR_TO_DATE(END_DATE, '%m/%d/%Y')) > latest_date_month THEN NET_PAT_REV_CC ELSE 0 END) / 1000000, 2), 'M') AS YTG,
  CONCAT(ROUND(SUM(NET_PAT_REV_CC) / 1000000, 2), 'M') AS REVENUE
FROM org_data
CROSS JOIN latest_year_month_day
GROUP BY YEAR(STR_TO_DATE(END_DATE, '%m/%d/%Y'))
ORDER BY YEAR;





